### ISSUE TITLE
Iron Router Authentication

### ISSUE THREAD

**Issue by helixzor32** [libreboard/libreboard#155]
So - I didn't really have any experience with iron router until implementing a version of Libreboard for my company. What I am not understanding is that when dealing with the ensuring a user is logged in and directing them accordingly.

http://libreboard.com/boards 

This does not trigger the onBeforeAction that would typically be triggered whenever you tried going to an existing board without being logged in (which would perform the whole "you can see it, but to do anything please sign in"). It just hangs and shows the loading graphic and hangs (assuming it is waiting on the subscription).

Is there a reason the onBeforeAction in main/routes.js is not getting triggered?

**Comment by mquandalle** [comment]
This is fixed in the Renaissance era :-)

**Comment by helixzor32** [comment]
Hey Max,

So our scenario is a bit messy. We pulled a libreboard version from you all awhile back (months and months ago) - and have since been making our own modifications / changes for our company - so I can't do a direct pull from this repo.

Can you direct me to exactly which changes on the Renaissance commit was what corrected the router issue? I'm assuming there were numerous other changes / fixes for other things you included on that commit.

Jeremy

**Comment by mquandalle** [comment]
Hello Jeremy,

I'm sorry you are in a messy state, the bug you are refferting to should be fixed with the following change:

```diff
@@ client/views/main/routers.js  @@
        Router.configure({
             redirectLoggedInUsers = options['redirectLoggedInUsers'];
  
         // redirect logged in users to Boards view when they try to open Login or Signup views
-       if (Meteor.user() && redirectLoggedInUsers) {
+       if (Meteor.userId() && redirectLoggedInUsers) {
            // redirect
            this.redirect('Boards');
            return;
         }
  
         // authenticated
-        if (!Meteor.user() && authenticate) {
+        if (!Meteor.userId() && authenticate) {

            // redirect
            this.redirect(authenticate);

            // options authenticate not next().
            return;
         }

-            if (!Meteor.user()) this.layout('layout');
+            if (!Meteor.userId()) this.layout('layout');
  
             // user found then AuthLayout render
             else this.layout('AuthLayout');
```

I hope you'll be able to switch back to mainstream release when we'll release v0.9 (including official docker image). Feel free to email me if you need some help for that. Out of curiosity, what modifications did you made to adapt LibreBoard to your company needs?

**Comment by helixzor32** [comment]
I added keyboard maneuvering / shortcuts to be able to perform actions on lists/boards/cards.

Ex: up,down,left, right to maneuver through lists and cards (enter triggering opening the cards)

Adding card search using the search input that was provided up on the top left. LDAP login was added for the sign up / login process with our local LDAP server. 

Other shortcuts:
'b' = back to boards, 'a c' = add card, 'a l' = add list, 'r+<number>' would allow a selected card to be ranked to a specific spot.

Just things in that nature.

Jeremy

**Comment by helixzor32** [comment]
Like I mentioned - our versions of the routers are probably outdated. I added the change you specified - but upon rebuilding - going to our /boards directory while not logged in still hangs.

Any ideas? 

main/routers.js
<pre>
/*
* If you want to use a default layout template for all routes you can
* configure a global Router option.
*/
Router.configure({
    loadingTemplate: 'loading',
    notFoundTemplate: 'notfound',

    yieldRegions: {
        '': {
            to: 'modal'
        }
    },

    /*
    * onBeforeAction hooks now require you to call this.next(),
    * and no longer take a pause() argument. So the default behaviour is reversed.
    * ClassMapper body add, remove class.
    */
    onBeforeAction: function(pause) {
        var body = $('body'),
            options = this.route.options,
            bodyClass = options["bodyClass"],
            authenticate = options['authenticated'],
            redirectLoggedInUsers = options['redirectLoggedInUsers'];

        // redirect logged in users to Boards view when they try to open Login or Signup views
        if (Meteor.userId() && redirectLoggedInUsers) {
            // redirect
            this.redirect('Boards');
            return;
        }

        // authenticated
        if (!Meteor.userId() && authenticate) {

            // redirect
            this.redirect(authenticate);

            // options authenticate not next().
            return;
        }

        // Remove class attribute body
        body.removeAttr('class');

        // if klass iron router name currentRouter then add Class
        if (bodyClass) body.addClass(bodyClass);

        // reset default sessions
        Session.set('error', false);
        Session.set('warning', false);

        Popup.close();

        // Layout template found then set render this.route options layout.
        if (!options.layoutTemplate) {

            // if user undefined then layout render
            if (!Meteor.userId()) this.layout('layout');

            // user found then AuthLayout render
            else this.layout('AuthLayout');
        }

        // Next
        this.next();
    }
});

Router.route('/', {
    name: 'Home',
    template: 'home',
    layoutTemplate: 'LandingLayout'
});
</pre>
